### ISSUE TITLE
分句建议

### ISSUE THREAD

**Issue by lianbook** [jing332/tts-server-android#10]
建议分句的时候不要以句号分割，可以两个符号一次。不然有时候太长可能超时卡住

**Comment by jing332** [comment]
我用逗号试过了，听起来断句太明显，而且请求太频繁还会被微软限制，所以没用。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月19日(周六) 下午3:07
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jing332/tts-server-android] 分句建议 (Issue #10)




 
建议分句的时候不要以句号分割，可以两个符号一次。不然有时候太长可能超时卡住

**Comment by lianbook** [comment]
那可不可以检测下分句的长度，如果超过多少就做成两次？

**Comment by jing332** [comment]
嗯这倒是可以



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月19日(周六) 下午3:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jing332/tts-server-android] 分句建议 (Issue #10)




 
那可不可以检测下分句的长度，如果超过多少就做成两次？

**Comment by lianbook** [comment]
这个可以优化，比如单句的字符长度30左右

**Comment by lianbook** [comment]
具体长度可以多测试下，再取优

**Comment by lianbook** [comment]
我看一个app应该多线程的吧，那可以考虑把分句取音频的再分多个线程，这样可以提前存一些音频就不容易断句也不会动不动卡半天了

**Comment by jing332** [comment]
本就是异步的，我用了生产者消费者模式



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月19日(周六) 下午3:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jing332/tts-server-android] 分句建议 (Issue #10)




 
我看一个app应该多线程的吧，那可以考虑把分句取音频的再分多个线程，这样可以提前存一些音频就不容易断句也不会动不动卡半天了

**Comment by lianbook** [comment]
生产者可以多搞几个人

**Comment by jing332** [comment]
微软有ip限制，多连接反倒会起反效果。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月19日(周六) 晚上10:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jing332/tts-server-android] 分句建议 (Issue #10)




 
生产者可以多搞几个人

**Comment by lianbook** [comment]
有些一段可能只有一到三四个字，也是调用一次么？

**Comment by jing332** [comment]
是的，没有长度判断。

**Comment by lianbook** [comment]
应该可以做到更智能才是…。还有一个就是ai学习深度学习的办法，做成可以识别男女对话就更好了

**Comment by jing332** [comment]
ai都不一定能准确识别，你们总是有一些莫名其妙要求。

**Comment by lianbook** [comment]
其实不用ai也能识别的，我看到了规律

**Comment by lianbook** [comment]
我只是希望，这个ap更强大

**Comment by lianbook** [comment]
这个先放一边吧，先吧那个一个字三五个字 调用一次的，改改吧

**Comment by jing332** [comment]
现在这样就知足吧🙄，而且小说角色对话规律并非固定的，识别起来又哪是那么容易

**Comment by jing332** [comment]
分句过短你得给我示例，而且这个有什么影响么？

**Comment by lianbook** [comment]
影响是不大，不过可以少调用几次，更稳定吧

**Comment by jing332** [comment]
找不到更好的解决办法，目前就这样吧
