### ISSUE TITLE
晓晓的风格列表和azure的语音库不一致，微软的多了个撒娇但是TTS加载不出来

### ISSUE THREAD

**Issue by linmister** [jing332/tts-server-android#104]
![image](https://github.com/jing332/tts-server-android/assets/51257978/1a45bbfc-ee55-49d9-b58c-59f6aed9b513)

**Comment by linmister** [comment]
![a14989fbefaf21a2d2ecfe2742edfc9](https://github.com/jing332/tts-server-android/assets/51257978/929e5f80-812b-4c06-aee7-acbcad77ca2b)
还有大佬问下之前Azure的演示接口晓晓有个温文合雅的风格，有没有办法出来

**Comment by jing332** [comment]
尝试清空软件缓存，然后换个Azure 地区Region试试
