### ISSUE TITLE
每次遇到一些特殊符号的时候，就会卡住

### ISSUE THREAD

**Issue by XY50** [jing332/tts-server-android#107]
每次遇到一些特殊符号的时候，就会卡住
![Screenshot_2023-07-31-12-55-27-635_com github jing332 tts_server_android](https://github.com/jing332/tts-server-android/assets/121076219/aa0fcfe2-89d9-47fe-8ac7-5ebfcc85e0cd)

**Comment by DaveScream** [comment]
You found why java handler hanging up

**Comment by jing332** [comment]
插件问题, 和程序无关，具体来说是文本中包含 SSML中格式的某些特殊符号，导致Azure服务器无法解析SSML

**Comment by jing332** [comment]
程序内置的于最新版Azure插件已针对ssml特殊符号进行替换处理，
当然，你也可用替换规则功能主动替换下

**Comment by XY50** [comment]
好的
