### ISSUE TITLE
您好，这个可以接管其他指向系统tts的app吗？

### ISSUE THREAD

**Issue by huangfubingbing** [jing332/tts-server-android#114]
我使用的是墨案的产品，但它使用的是精简版的安卓8.1，原生的无障碍功能都被移除了，包括语音设置。一些app只能调用系统tts,不能手动设置朗读引擎，所以点击播放会没反应。   我用这个软件设置好系统tts后，还是没反应，检测不到文字转语音设置。

**Comment by jing332** [comment]
@huangfudadi 如果是听书推荐用开源阅读APP，它内置了网络引擎功能，这样无需设为系统TTS即可使用TTS Server
您可通过TTS Server内的 系统TTS转发器 功能进行导入阅读APP使用。

**Comment by huangfubingbing** [comment]
> @黄福大地如果是听书推荐用开源阅读APP，它内置了网络引擎功能，这样需要设置系统TTS就可以使用TTS服务器您可以通过TTS服务器内部的系统TTS转发器功能进行导入阅读APP使用 。

我的阅读app使用正常，而且阅读可以手动选择第三方本地tts。但是 静读天下好像只能使用 系统的文字转语音设置，问题在于墨案这精简系统给精简掉了，不能在设置里手动选择引擎，点播放会没反应。

**Comment by huangfubingbing** [comment]
> @黄福大地如果是听书推荐用开源阅读APP，它内置了网络引擎功能，这样需要设置系统TTS就可以使用TTS服务器您可以通过TTS服务器内部的系统TTS转发器功能进行导入阅读APP使用 。

感谢你的帮助，我使用 ADB命令  把默认tts改成第三方本地tts后，可以正常播放了。
