### ISSUE TITLE
这张857K的图片有啥用？徒增安装包内存

### ISSUE THREAD

**Issue by XY50** [jing332/tts-server-android#116]
这张857K的图片有啥用徒增安装包内存？试了一下删除没任何影响
![Screenshot_2023-08-27-02-45-45-962_bin mt plus canary-edit](https://github.com/jing332/tts-server-android/assets/121076219/a356f99b-01b4-4a80-9a0a-2ffa3d6578fc)
![Screenshot_2023-08-27-02-52-21-321_mark via](https://github.com/jing332/tts-server-android/assets/121076219/ff807fd4-db1f-4a2d-8f7b-f0bed65313a1)

**Comment by jing332** [comment]
等UI重写完毕，各种drawable和布局xml文件都会移除。

**Comment by XY50** [comment]
哦
