### ISSUE TITLE
最新开发版本的插件变量输入框无法粘贴

### ISSUE THREAD

**Issue by linmister** [jing332/tts-server-android#118]
1 最新开发版本的插件变量输入框无法粘贴
2 导入原配置后角色编辑中风格选择中无可选项
3 调整配置后开启朗读会异常加速几秒钟就读过好几页文字，但没有任何语音

**Comment by jing332** [comment]
1. Android ComposeUI 框架问题，目前无法解决，使用输入法剪贴板代替。

2. 发音人不支持 (UI未更新bug)

3. 没有日志，不知道
