### ISSUE TITLE
点击加号新建声音出现崩溃，反复尝试都一样。

### ISSUE THREAD

**Issue by 5528046** [jing332/tts-server-android#12]
2022-11-20T05:35:29.150
版本代码：2， 版本名称：0.1_202211161018
崩溃详情：
go.Universe$proxyerror: Get "https://speech.platform.bing.com/consumer/speech/synthesize/readaloud/voices/list?trustedclienttoken=6A5AA1D4EAFF4E9FB37E23D68491D6F4": x509: certificate signed by unknown authority
	at tts_server_lib.Tts_server_lib.getEdgeVoices(Native Method)
	at y1.b.j(SourceFile:606)
	at i3.a.x(Unknown Source:8)
	at y3.g0.run(SourceFile:101)
	at d4.a$a.run(SourceFile:82)
	Suppressed: y3.e0: [i1{Cancelling}@36dba3f, Dispatchers.Default]

**Comment by jing332** [comment]
证书校验失败，所有接口都这样么？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月20日(周日) 凌晨5:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jing332/tts-server-android] 点击加号新建声音出现崩溃，反复尝试都一样。 (Issue #12)




 
2022-11-20T05:35:29.150
 版本代码：2， 版本名称：0.1_202211161018
 崩溃详情：
 go.Universe$proxyerror: Get "https://speech.platform.bing.com/consumer/speech/synthesize/readaloud/voices/list?trustedclienttoken=6A5AA1D4EAFF4E9FB37E23D68491D6F4": x509: certificate signed by unknown authority
 at tts_server_lib.Tts_server_lib.getEdgeVoices(Native Method)
 at y1.b.j(SourceFile:606)
 at i3.a.x(Unknown Source:8)
 at y3.g0.run(SourceFile:101)
 at d4.a$a.run(SourceFile:82)
 Suppressed: y3.e0: ***@***.***, Dispatchers.Default]

**Comment by jing332** [comment]
APP内检查更新有问题么？比如提示检查更新失败之类的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月20日(周日) 凌晨5:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jing332/tts-server-android] 点击加号新建声音出现崩溃，反复尝试都一样。 (Issue #12)




 
2022-11-20T05:35:29.150
 版本代码：2， 版本名称：0.1_202211161018
 崩溃详情：
 go.Universe$proxyerror: Get "https://speech.platform.bing.com/consumer/speech/synthesize/readaloud/voices/list?trustedclienttoken=6A5AA1D4EAFF4E9FB37E23D68491D6F4": x509: certificate signed by unknown authority
 at tts_server_lib.Tts_server_lib.getEdgeVoices(Native Method)
 at y1.b.j(SourceFile:606)
 at i3.a.x(Unknown Source:8)
 at y3.g0.run(SourceFile:101)
 at d4.a$a.run(SourceFile:82)
 Suppressed: y3.e0: ***@***.***, Dispatchers.Default]

**Comment by jing332** [comment]
我把证书校验关闭了，你再试试看：https://github.com/jing332/tts-server-android/actions

**Comment by 5528046** [comment]
一直提示检查更新失败

**Comment by 5528046** [comment]
还是崩溃的

**Comment by 5528046** [comment]
找到原因了，我的adguard默认开启https过滤，关了就能用了，谢谢
