### ISSUE TITLE
段落越长，朗读时间间隔也越长

### ISSUE THREAD

**Issue by shadwo1** [jing332/tts-server-android#122]
开启了流式播放音频，朗读间隔没有变化.

使用的软件是 阅读。

我测试时一个段落有570字，朗读这段时，只经过了一段时间的间隔，就自动跳到下一段。

**Comment by shadwo1** [comment]
增加拆分段落、句子规则后可以正常朗读。

**Comment by nhan000** [comment]
(我在用翻译器)

你好，你使用的应用是这个吗？https://github.com/gedoor/legado

你能向我展示一下你是如何添加分段和句子规则的吗？还有，什么是流媒体音频设置？非常感谢！

**Comment by shadwo1** [comment]
> 示一下你是如何添加分段和句子规则的吗？还有，什么是流媒体音频设置？非常感谢！

Do you solve that? I was using the rules uploaded by others.
In my experience, you don't need to use these rules. You can just check the option: "Split long sentences'.

**Comment by shadwo1** [comment]
> ，什么是流媒体音频设置？

'stream audio' option in the tts server's setting.

**Comment by nhan000** [comment]
Thanks for your reply. Besides this issue, another main one I have is that it pauses a lot at the end of each sentence. Checking the option: “Split long sentences” didn't solve this unfortunately. I'll probably just not use TTS Server.

**Comment by eromoe** [comment]
目前确实是在每句话（回车）之后停顿很长，非常明显的停顿，主要是停的太长了。
