### ISSUE TITLE
默认的配置问题

### ISSUE THREAD

**Issue by lianbook** [jing332/tts-server-android#13]
![Screenshot_2022-11-20-08-31-57-644_com github jing332 tts_server_android](https://user-images.githubusercontent.com/118592288/202877036-7ff2fe2d-5fba-4270-89d8-4ce5ee6b5284.jpg)
如果不设置对话和和旁白，就会直接使用默认，而不是设置的模式

>

**Comment by jing332** [comment]
右上角菜单把多语音选项关掉



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月20日(周日) 上午8:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jing332/tts-server-android] 默认的配置问题 (Issue #13)




 

 如果不设置对话和和旁白，就会直接使用默认，而不是设置的模式

**Comment by jing332** [comment]
此问题解决了么？

**Comment by lianbook** [comment]
我直接弄了俩同音色一个旁白，一个对话

**Comment by lianbook** [comment]
最近在用百度接口，稳定速度快
