### ISSUE TITLE
沒有正在使用任何有朗讀功能的應用，TTS server卻突然自己跑了起來，並且出現Null Pointer Exception。

### ISSUE THREAD

**Issue by chokhocheung** [jing332/tts-server-android#141]
如題，截圖如下：

![IMG_20240119_080226](https://github.com/jing332/tts-server-android/assets/101919798/0ad5bca4-1bb1-4276-a4f4-2e2d2062a426)

使用的版本是1.24.011308 (902)。
謝謝！

**Comment by jing332** [comment]
@chokhocheung tts server无权限自启动，仅可由系统服务调用，所以此问题与tts server无关。
