### ISSUE TITLE
[mp3 bgm] https://bin.kv2.dev/~65b3366a5de7ed6bfdbc6fd0

### ISSUE THREAD

**Issue by mablue** [jing332/tts-server-android#144]
[mp3files.zip](https://github.com/jing332/tts-server-android/files/14060578/mp3files.zip)

https://bin.kv2.dev/~65b3366a5de7ed6bfdbc6fd0

**Comment by jing332** [comment]
File picker cannot get original path, try use `internal file picker` .

**Comment by mablue** [comment]
![Screenshot_۲۰۲۴۰۱۲۹-۱۰۵۳۲۷_TTSFarsi Server](https://github.com/jing332/tts-server-android/assets/5004900/9ebe9cc0-8246-4eae-8bed-49cce89ccc7e)
all files permission was given but I have nothing.
android 13 crdroid rom mi 9t pro

**Comment by jing332** [comment]
Do you have the `disable FUSE` magisk plug-in installed on your device?

As far as I know, on Redmi Note9, after installing a similar plug-in to disable FUSE, you will not be able to obtain the file directory.

**Comment by jing332** [comment]
Do not put mp3 files in public folders (e.g: `Downloads, Documents`).

And when selecting files, do not choose from `Recent files` or `Downloaded content`. Instead, manually enter the folder to select

**Comment by mablue** [comment]
No I am not rooted and not installed magisk
Ok I will try with internal storage option
.
.
.
fixed
