### ISSUE TITLE
考虑不考虑加一些其他的接口？

### ISSUE THREAD

**Issue by lianbook** [jing332/tts-server-android#15]
比如百度的接口就有很多音色，国内的接口优势就是不卡稳定
或者谷歌的接口

{
  "concurrentRate": "0",
  "contentType": "audio/wav",
  "enabledCookieJar": false,
  "header": "",
  "id": -100,
  "lastUpdateTime": 1668975751716,
  "loginCheckJs": "",
  "loginUi": "",
  "loginUrl": "",
  "name": "1.百度-评书",
  "url": "http://tsn.baidu.com/text2audio,{\n    \"method\": \"POST\",\n    \"body\": \"tex={{java.encodeURI(java.encodeURI(speakText))}}&spd={{(speakSpeed + 5) / 10 + 4}}&per=4114&cuid=baidu_speech_demo&idx=1&cod=2&lan=zh&ctp=1&pdt=220&vol=5&aue=6&pit=5&_res_tag_=audio\"\n}"
}

**Comment by jing332** [comment]
程序拓展性低，现在要加进去会改动很多地方，特别是UI。
有这精力都能够再开发出个全新APP了。

**Comment by jing332** [comment]
可能我说的有些夸张了，这样也未尝不可。
可以加一个自定义网络TTS功能，和微软TTS共存并适配原有功能（如多语音）。
不过，这样的话原有配置文件结构都得改动了，我得仔细想想思路。

**Comment by lianbook** [comment]
![Uploading Screenshot_2022-11-22-03-02-37-022_com.microsoft.emmx.jpg…]()
亚马逊每个月500万字免费

**Comment by limne** [comment]
抖音火山引擎有几个声音不错。

**Comment by lianbook** [comment]
> 抖音火山引擎有几个声音不错。

是免费没什么限制么？

**Comment by jing332** [comment]
八成是有加密的，白嫖不成😅

**Comment by jing332** [comment]
@lianbook  最新Dev版已加入自定义TTS功能：https://github.com/jing332/tts-server-android/actions

**Comment by jing332** [comment]
另外提一嘴，百度TTS的 `aue=6` 参数为音频格式，可选1-6， 有raw、mp3、opus等，如果播放破音、开头有噪音就尝试打开/关闭解码，如果音调异常就换采样率。

**Comment by lianbook** [comment]
阿里的接口是免费的。
