### ISSUE TITLE
Built-in tts language selection issue with search

### ISSUE THREAD

**Issue by mablue** [jing332/tts-server-android#153]
https://github.com/jing332/tts-server-android/actions/runs/7696405021

this last dev version have issue in set correct selected language (for example فارسی with searching فا resets to africans lng) in built-in tts language selection. I have this issue in other languages search too

**Comment by jing332** [comment]
Could you please provide a screencast video demonstrating the issue?

**Comment by jing332** [comment]
https://github.com/jing332/tts-server-android/issues/154#issuecomment-1918455490
