### ISSUE TITLE
插件tts在2月4日起无法使用，无法朗读，也无法添加插件tts

### ISSUE THREAD

**Issue by kdgsh** [jing332/tts-server-android#159]
之前一直正常
https://bin.kv2.dev/~65c06c775de7ed6bfdbd0888
https://bin.kv2.dev/~65c06c755de7ed6bfdbd0887

**Comment by kdgsh** [comment]
补充一下只是azure的插件tts

**Comment by jing332** [comment]
`failed to connect to eastasia.tts.speech.microsoft.com/20.6.139.246 (port 443) from /10.80.30.76 (port 37036) after 10000ms https://eastasia.tts.speech.microsoft.com/cognitiveservices/voices/list`

加载语音列表数据超时，很明显是你的网络问题

**Comment by kdgsh** [comment]
我网络在其他应用正常。我尝试过挂梯，也不行。确实是网络问题，可能出在azure或别的地方。我等几天看看吧，打扰您了。
