### ISSUE TITLE
请问能不能开机自启动的时候直接启动服务

### ISSUE THREAD

**Issue by X22372** [jing332/tts-server-android#16]
你好，我目前的方法是用自动化软件tasker，打开应用，点击启动，返回主界面，请问有没有更好的方法比如发个intent之类的，或者直接应用内弄个选项

**Comment by jing332** [comment]
我可以把server的服务导出，这样其它应用就可以用Intent直接启动。

**Comment by jing332** [comment]
https://github.com/jing332/tts-server-android/actions/runs/3510994308/jobs/5881339213

**Comment by X22372** [comment]
好的，试了下可以了，感谢感谢

**Comment by lianbook** [comment]
怎么弄得？

**Comment by X22372** [comment]
> 怎么弄得？

包：com.github.jing332.tts_server_android
类：com.github.jing332.tts_server_android.service.TtsIntentService
目标：service
发送intent就行，记得用最新的测试版
