### ISSUE TITLE
最新开发版，拖动有bug，

### ISSUE THREAD

**Issue by 550-q** [jing332/tts-server-android#165]
拖动项目时，项目会乱跳甚至会被打断，分组排序也会乱。
朗读规则、插件,替换规则界面项目拖动都有相同问题。
（如gif图，请注意开头时分组的排序）
![Gif_20240213011738.gif](https://github.com/jing332/tts-server-android/assets/122971571/ff8f1461-dca6-4677-88a0-e92c987d1ae7)

**Comment by jing332** [comment]
没法修，代价太大

**Comment by 550-q** [comment]
> 没法修，代价太大

那替换规则的手动排序不能保存排序结果的bug能修复吗？
现在最新开发版的替换规则手动排序（包括置顶）无法保存结果，排好序退出替换规则界面再进去顺序又乱了。
