### ISSUE TITLE
添加自定义tts奔溃了一次

### ISSUE THREAD

**Issue by lianbook** [jing332/tts-server-android#17]
https://bin.kv2.dev/~6381ad8be599576ea02b27d2

**Comment by lianbook** [comment]
你那个自定义tts.的有问题的

**Comment by lianbook** [comment]
![Screenshot_2022-11-26-14-15-29-854_io legado app release](https://user-images.githubusercontent.com/118592288/204075095-c8fb6437-62e9-4b63-876d-20745df9d7c5.jpg)
这个还有一个content type   如果没有这个参数，应该不行

**Comment by jing332** [comment]
系统TTS实现方式不一样，MediaCodec会自动识别格式

**Comment by lianbook** [comment]
用你那个例子你测试成功了么？我这边尝试了你那个例子是不行的

**Comment by jing332** [comment]
如图

**Comment by lianbook** [comment]
新版的阅读你试试

**Comment by jing332** [comment]
把解码音频打开

**Comment by jing332** [comment]
这和阅读版本没关系

**Comment by lianbook** [comment]
新版的阅读你试试
![Screenshot_2022-11-26-14-29-17-324_com github jing332 tts_server_android](https://user-images.githubusercontent.com/118592288/204075519-874a6985-5352-400c-8190-9ff302d9d483.jpg)
所有的都尝试了，每个都测试失败

**Comment by jing332** [comment]
没有原因么？

**Comment by jing332** [comment]
![image](https://user-images.githubusercontent.com/42014615/204075748-64799768-407a-4809-bdaa-afc233b974a0.png)
我测试没问题 16000hz， 打开解码

**Comment by lianbook** [comment]
你那个不是百度接口
![Uploading Screenshot_2022-11-26-14-45-03-250_com.github.jing332.tts_server_android.jpg…]()

**Comment by jing332** [comment]
注意看上面 我用多语音: edge和百度

**Comment by lianbook** [comment]
![Screenshot_2022-11-26-14-49-16-481_com github jing332 tts_server_android](https://user-images.githubusercontent.com/118592288/204076230-84c1788a-b8f4-4977-a0c0-3e5221e4155c.jpg)
这里一直在创建，啥情况

**Comment by jing332** [comment]
不是这个日志 系统TTS配置的

**Comment by jing332** [comment]
那只是Go的信息日志

**Comment by lianbook** [comment]
我微信18907925559

**Comment by lianbook** [comment]
![Uploading Screenshot_2022-11-26-15-08-14-876_com.github.jing332.tts_server_android.jpg…]()

**Comment by lianbook** [comment]
获取音频失败: 就好像是江寻月自己朝着拳头冲上去一般。 
websocket: close 1007 (invalid payload data): Unsupported voice zh-CN-XiaomiNeural.

**Comment by lianbook** [comment]
![Uploading Screenshot_2022-11-26-15-32-58-127_com.github.jing332.tts_server_android.jpg…]()

**Comment by lianbook** [comment]
![Screenshot_2022-11-26-15-37-46-497_com github jing332 tts_server_android](https://user-images.githubusercontent.com/118592288/204077864-f19b8a9b-e619-446b-96b0-ee91a0ec742d.jpg)

**Comment by jing332** [comment]
编辑界面的 `测试` 有问题么

**Comment by lianbook** [comment]
这里太卡了，https://aj8.cn/thread-48.htm 来这里聊吧

**Comment by jing332** [comment]
找到问题了 开发环境没问题, 应是打包时混淆压缩代码导致的

**Comment by jing332** [comment]
> 你这都开源的，没必要压缩混淆吧？

压缩可以减小apk体积，混淆代码可以提升性能。

**Comment by lianbook** [comment]
新问题截图已经发那个链接了，你看看这边上传速度太慢了

**Comment by jing332** [comment]
> 新版好像还是不行…

嗯 漏掉了一处

**Comment by jing332** [comment]
加上了 这回等构建完再看看吧
另外提一嘴 如果github太卡，可以直接回复邮件。会自动转发到Issue

**Comment by jing332** [comment]
成了

**Comment by lianbook** [comment]
请看那个帖子

**Comment by lianbook** [comment]
现在成了？？

**Comment by jing332** [comment]
嗯，最新actions，我测试没问题

**Comment by lianbook** [comment]
之前的你都没测试吧😥😥哪个邮件？

**Comment by jing332** [comment]
就是github绑定的邮箱
是最新的0.1_202211261645，之前那两个版本都不行。

**Comment by lianbook** [comment]
你绑定了哪个邮箱，我第一次注册这个。。。
自定义的无法设置对话旁白，你那边是怎么和微软的同时朗读的？

**Comment by lianbook** [comment]
per是音色的参数

**Comment by lianbook** [comment]
per 度逍遥（精品）=5003，度小鹿=5118，度博文=106，度小童=110，度小萌=111，度米朵=103，度小娇=5


度小宇=1，度小美=0，度逍遥（基础）=3，度丫丫=4，精品音库：度逍遥（精品）=5003，度小鹿=5118，度博文=106，度小童=110，度小萌=111，度米朵=103，度小娇=5

**Comment by lianbook** [comment]
算了，就这样吧！

**Comment by jing332** [comment]
> 你绑定了哪个邮箱，我第一次注册这个。。。 自定义的无法设置对话旁白，你那边是怎么和微软的同时朗读的？

就正常配置，可能是没更新上，重启朗读试试。
