### ISSUE TITLE
app内播放音频问题

### ISSUE THREAD

**Issue by limne** [jing332/tts-server-android#18]
第一个是声音会变小，过一会又正常了，会反复出现；
第二个是webm格式看阅读app内跳段时间应该是播放了，但听不到声音，网页测试webm是正常的；
第三个是听着每一段最后几个字好像没播放完就下一段了。

**Comment by jing332** [comment]
这几个问题我都解决不了，1和3都无法在我的设备复现，毫无头绪

**Comment by jing332** [comment]
新版成功换上ExoPlayer了，webm在我设备是没问题了。
问题3应该也可解决。

**Comment by limne** [comment]
好的，我试试，谢谢大佬。

**Comment by limne** [comment]
测试好了，三个问题都没了，非常完美，流量最小，音质不变，还最连贯。

**Comment by jing332** [comment]
APP内播放，有没有遇到朗读突然卡住的情况？我猜测是朗读完毕的通知没触发
