### ISSUE TITLE
每段朗读时间再缩短点么？

### ISSUE THREAD

**Issue by lianbook** [jing332/tts-server-android#19]
现在每段朗读间隔大约1.5到两秒左右。自定义接口间隔更久。可以吧这个时间再缩短点么？缩短到0.3-0.5秒左右

**Comment by jing332** [comment]
我没有设置间隔

**Comment by limne** [comment]
这个应该是网络延时，用webm-24khz-16bit-24kbps流量小，响应时间最快。

**Comment by jing332** [comment]
看日志，有显示耗时

**Comment by limne** [comment]
显示握手失败，是微软限制的吧？

**Comment by lianbook** [comment]
段落之间的间隔比，句子之间的朗读间隔不一样。你们听出来没有？

**Comment by jing332** [comment]
是的句子也有间隔，这大概是解码播放的延迟，也不排除是音频头部有空白时间。

**Comment by jing332** [comment]
嗯，IP被限制就会握手失败

**Comment by lianbook** [comment]
如果多个，短的小段合并成一个中等的段落去合成音频。应该就会好很多。
希望作者可以考虑考虑

**Comment by limne** [comment]
阅读app是按段落送的，延迟明显的话，说明网络不太好，换成国内百度的就会发现没有任何间隔时间了。

**Comment by limne** [comment]
> 嗯，IP被限制就会握手失败

还好，wifi+数据，有三条线路可选。

**Comment by lianbook** [comment]
我就是用阅读的app，用tts server生成的接口。这样句子之间没什么延迟，但是这样段落之间有些延迟…tts自带这个总比按句来阅读的好点吧

**Comment by lianbook** [comment]
都是提前把之前的音频下载好的。为何百度的段落间的延迟小一些？

**Comment by lianbook** [comment]
如果我把整个章节的句号都净化掉会怎样？？

**Comment by lianbook** [comment]
新版似乎好点。我现在直接净化规则吧句号净化成逗号了

**Comment by jing332** [comment]
可能和音频格式有关系

**Comment by lianbook** [comment]
![Screenshot_2022-12-05-22-06-32-988_com github jing332 tts_server_android](https://user-images.githubusercontent.com/118592288/205656755-cc0658f8-e5f7-42e5-a3f1-3c285d3d425c.jpg)
这个自定义的tts无法设置对话旁白？

**Comment by lianbook** [comment]
长按设置了，但是还是无法朗读，直接崩了

**Comment by jing332** [comment]
已测试最新正式版无问题
需要日志，以及配置

**Comment by jing332** [comment]
你只设置了对话，没设置为旁白。
为空表示朗读全部，而多语音只会从对话/旁白里找启用的配置。

**Comment by lianbook** [comment]
![Screenshot_2022-12-08-02-58-07-763_com github jing332 tts_server_android](https://user-images.githubusercontent.com/118592288/206271388-54877a56-2f4d-45cb-b60f-ad7b04a76dc7.jpg)

这样设置了，还是会崩溃

**Comment by jing332** [comment]
没日志，无法复现

**Comment by jing332** [comment]
你这样啥信息都没有我也无法。
自定义TTS单语音情况下有问题吗？
都开了哪些选项？如分割长句，APP内播放？

**Comment by Ben1000ten** [comment]
> 

每一句朗读间隔时间太长了，能不能预加载后面的朗读内容?

**Comment by jing332** [comment]
> > 
> 
> 每一句朗读间隔时间太长了，能不能预加载后面的朗读内容?

见 https://github.com/jing332/tts-server-android/issues/20#issuecomment-1340586095

**Comment by lianbook** [comment]
哎，可能是系统版本之类问题。 都试过了，算了不折腾了。够用了
