### ISSUE TITLE
朗读完一章会暂停，需要主动打开tts-server界面

### ISSUE THREAD

**Issue by limne** [jing332/tts-server-android#2]
使用阅读app听小说过程中发现，每听完一章，需要手动打开tts-server界面，才会继续朗读，就打开界面过一会儿会看到下一章发送消息的日志开始输出，如果不手动打开会一直停在那里。据我观察，阅读app使用url朗读这种方式和使用系统tts组件朗读不同，前者是异步的，每次发送一段，发送和接收是异步的，一章的内容会早早发送完，然后收到一段响应的音频就播放，整体上就很连贯，后者应该是同步的，网络越差两段朗读的间隔时间就越长。
会不会是阅读app早早把一章发送完，也接收完响应的音频，tts-server空闲的时间过长之后就休眠了？

**Comment by limne** [comment]
浏览器里输入url打不开，从tts-server里右上的菜单可以打开，打开后测试播放正常，和导入url差不多的问题。
另外，azure/creation接口不能支持里面列出的一些音频格式，比如ogg-24khz-16bit-mono-opus，貌似只支持edge的三种格式。

**Comment by limne** [comment]
浏览器里输入url打不开，从tts-server里右上的菜单可以打开，打开后测试播放正常，和导入url差不多的问题。
另外，azure/creation接口不能支持里面列出的一些音频格式，比如ogg-24khz-16bit-mono-opus，貌似只支持edge的三种格式。

**Comment by limne** [comment]
昨晚又试了导入url，每次只能在开启服务时导入一个，紧接着导入第二个就不行，必须重启服务，看来和后台休眠没关系，貌似是导入第二个连接不上tts-server服务端。
音频格式，我试了下，edge支持那三种，creation只支持MP3，azure支持列出的所有格式，我用过的最好的就是倒数第二个ogg-24khz-16bit-mono-opus，音质和流量正好平衡。
后台设置我检查过，电池优化、活动暂停、后台锁都设置好了，每次一章朗读完，暂停的时候，打开tts-server app的时候，服务是启动的，没有被x掉，也没有休眠，过一会儿就看到日志输出，然后就听到声音了，也可能是每章第一次请求延时比较长，我再看看是不是。

**Comment by limne** [comment]
刚才正好一章读完，等了几分钟没啥反应，阅读app里面暂停在开始反复两次也没反应，然后切到tts-server就好了。

**Comment by limne** [comment]
这个没试过，试过导入失败后，粘贴url到浏览器里也打不开。
每章读完卡住的问题，我又注意了几次，有一次是自动到下章，看来和app闲置时间太长可能有关，能不能设置一个看门狗之类的可以自己设置定时检查唤醒服务状态？

**Comment by limne** [comment]
我看是前台服务，看应用通知里设置是禁用的，权限管理显示没有申请任何权限，是不是加个重要级别的通知就可以了？其他有关设置我检查过没啥问题。

**Comment by limne** [comment]
刚才日志报了个不支持超过300，当前长度302的错误，我看最新的版本不是处理过了吗？

**Comment by limne** [comment]
本来想复制日志，但复制不了很快就过去了，日志可以设置级别，默认只显示异常和错误的，这样日志量小一些，可以打包发给你。从测试页面试了下，360个汉字都没有问题，但早上听小说的时候确实发现了报了个超长的错，下次出现我把内容贴到测试页面试试。

**Comment by limne** [comment]
我手机是安卓13，tts-server通知打不开，显示灰色

**Comment by limne** [comment]
我把“允许完全后台”开关打开，正常了，但估计有点费电，发不了截图。。。。

**Comment by limne** [comment]
看到了，只差通知打不开，其他都没问题

**Comment by limne** [comment]
刚才安装这个url的了，可以打开通知了，应该完美了，感谢之至！

**Comment by limne** [comment]
这个13的app不在release，可以release了，通知正常。

**Comment by a1one9** [comment]
把音频采样率后面的直接播放的对勾去掉, 就不会朗读完每章卡住了.

**Comment by Crzq** [comment]
> 把音频采样率后面的直接播放的对勾去掉, 就不会朗读完每章卡住了.

请问在哪里设置这个
