### ISSUE TITLE
在设置界面切换后台，每次切换都会自动随机开关下面的各种按钮

### ISSUE THREAD

**Issue by XY50** [jing332/tts-server-android#209]
在设置界面切换后台，每次切换都会自动随机开关下面的各种按钮

https://github.com/user-attachments/assets/b06dae72-85a6-40ae-8be6-1cf794b77438

**Comment by jing332** [comment]
噗，好有意思的bug，我无法复现。

**Comment by XY50** [comment]
我的问题，为了定位bug，我测试了安卓5、7、8、12、和两台13发现只有我用的这台安卓13的手机有这个问题，经过进一步的排除，最后才发现是跳过广告的软件GKD识别了设置中的跳过请求无声文本,导致出现了这个乌龙Bug
