### ISSUE TITLE
一直提示这个错误

### ISSUE THREAD

**Issue by czdj2000** [jing332/tts-server-android#21]
获取音频失败(Azure): x509: certificate signed by unknown authority

换不同的引擎也是

**Comment by jing332** [comment]
检查防火墙，广告拦截和杀毒软件

**Comment by jing332** [comment]
善用Github搜索功能
https://github.com/jing332/tts-server-android/issues/12#issuecomment-1321024557

**Comment by czdj2000** [comment]
确实adguard的原因，万分感谢！
