### ISSUE TITLE
希望添加试听

### ISSUE THREAD

**Issue by Chyiga-n** [jing332/tts-server-android#23]
声音多，风格更多，如果有试听就好了

**Comment by jing332** [comment]
开发版本已加，稍后更新

**Comment by jing332** [comment]
https://github.com/jing332/tts-server-android/actions/runs/3729500230

**Comment by jing332** [comment]
测试播放按钮在编辑界面的最底部

**Comment by Chyiga-n** [comment]
秒回复啊这是，有试听选择起来就省事多了，谢谢作者大大！

**Comment by Ben1000ten** [comment]
> 测试播放按钮在编辑界面的最底部

可以在多音字替换的界面也加一个试听吗？

**Comment by jing332** [comment]
这没啥必要吧，主要加起来也比较麻烦
