### ISSUE TITLE
新的分组功能无障碍

### ISSUE THREAD

**Issue by xyzz2001** [jing332/tts-server-android#26]
大佬如果有时间的话，可以在修复下无障碍吗？
在新的开发版中，分组不管是展开还是收起状态，都会朗读成展开状态。
分组后面的复选框也可以简化一下，从分组是否勾选，复选框已经选中改成分组复选框一选中就行了，等于说给软件加上了复选框，我们这边就会提示他是选中的还是未选中的。
谢谢。

**Comment by jing332** [comment]
好的，我看看

**Comment by jing332** [comment]
刚体验了下无障碍，确实需要完善，还有滑动条那里也不友好

**Comment by xyzz2001** [comment]
> 刚体验了下无障碍，确实需要完全善，还有滑动条那里也不好

其他地方都挺好的，那个进度条，我们的国内屏幕阅读器是可以用左右手试来滑动的，所以那个没有关系。感谢！

**Comment by jing332** [comment]
> > 刚体验了下无障碍，确实需要完全善，还有滑动条那里也不好
> 
> 其他地方都挺好的，那个进度条，我们的国内屏幕阅读器是可以用左右手试来滑动的，所以那个没有关系。感谢！

更新了：https://github.com/jing332/tts-server-android/actions/runs/3740864072
这次主要优化了滑动条变更时的朗读文本

**Comment by xyzz2001** [comment]
> > > 刚体验了下无障碍，确实需要完全善，还有滑动条那里也不好
> > 
> > 
> > 其他地方都挺不错的，那个进度条，我们的国内屏幕阅读器是可以用左手试来滑的，所以那个没有关系。谢谢！
> 
> 更新了：https://github.com/jing332/tts-server-android/actions/runs/3740864072 这次主要优化了滑动条变化更及时的朗读文本

我更新尝试了一下，新版复选框已经解决了。
滑动条有一个小问题，就是用屏幕阅读器的手势来滑动例如，定位到滑动条之后左滑，右滑会调整滑动条，但是不会有提示，但是已经修改了进度，但是点保存之后进度是不会生效的。
大佬可以明天有空的时候看一下，我这边也提供一个屏幕阅读器软件。
进软件之后可以在语音设置主语音库那边选择手机系统的语音库即可，默认的有点难听，哈哈。
文件：解说_20221214.apk
https://wwvr.lanzouw.com/i9lV80j381uh
共 1 项内容

**Comment by xyzz2001** [comment]
> 我用的TalkBack测试没问题，看来还是兼容性问题。

talk back，也只能用双指长按，然后左右拉来调那个进度，有一个手势来条进度的功能也是不可用的，就是按音量键。也可以调节净度条的功能。
已经很好用了，大佬尽量看看能不能修吧，修不了也没关系，也是可以操作的。
比大厂适配无障碍速度还快。

**Comment by jing332** [comment]
已更新滑动条：https://github.com/jing332/tts-server-android/actions/runs/3749641193

**Comment by jing332** [comment]
还有哪里需要无障碍优化吗？我一并解决掉。

**Comment by xyzz2001** [comment]
> 还有哪里需要无障碍优化吗？我一并解决掉。

暂时没发现问题了，非常感谢。
