### ISSUE TITLE
希望编辑内置TTS那几个组合框上面可以增加这些提示，以方便小白判断到底是什么

### ISSUE THREAD

**Issue by zmyznu** [jing332/tts-server-android#27]
无障碍里边能不能再增加几个东西？你比如说，分组下拉列表默认分组，选择角色下拉列表小双，选择语气下拉列表什么什么什么，无下拉列表，什么什么音频格式下拉列表什么什么等等

**Comment by jing332** [comment]
我用TalkBack无障碍套件，是有提示下拉列表的。 比如选中语言框时提示: 中文（普通话，简体），下拉列表语言

**Comment by zmyznu** [comment]
饿，我再测试一下其他，读屏

**Comment by jing332** [comment]
已更新无障碍下拉框: https://github.com/jing332/tts-server-android/actions/runs/3749641193

**Comment by jing332** [comment]
还有哪里需要无障碍优化吗？我一并解决掉。
