### ISSUE TITLE
是否可以选择忽视注释数字

### ISSUE THREAD

**Issue by bnlife** [jing332/tts-server-android#28]
注释如［34］会被直接读出数字

**Comment by jing332** [comment]
你可以自行用正则替换功能删掉注释

**Comment by XY50** [comment]
> 你可以自行用正则替换功能删掉注释

可不可以自带几个正则表达式的替换规则例式，小白表示不会用正则表达式，如果有列子的话，可以方便参考如何使用

**Comment by zmyznu** [comment]
这真是个好建议

**Comment by jing332** [comment]
@XY50  @zmyznu 
我本人也不太会正则表达式，就看有没有人整理了。

**Comment by jing332** [comment]
`\[[0-9]*\]`
这是 匹配 `[` 开头， `]` 结尾，中间为纯数字的正则表达式

**Comment by XY50** [comment]
> `\[[0-9]*\]` 这是 匹配 `[` 开头， `]` 结尾，中间为纯数字的正则表达式

这个怎么用？怎么改音调都没任何变化
![Screenshot_2022-12-25-15-58-48-726_com github jing332 tts_server_android-edit](https://user-images.githubusercontent.com/121076219/209460945-ef74598f-8b3b-4a7a-95a2-c9316da7f17a.jpg)

**Comment by XY50** [comment]
> `\[[0-9]*\]` 这是 匹配 `[` 开头， `]` 结尾，中间为纯数字的正则表达式
![Screenshot_2022-12-25-18-30-53-673_com github jing332 tts_server_android](https://user-images.githubusercontent.com/121076219/209464545-b8798b79-f5e3-48b3-ad1b-ced12ebeb6e4.jpg)

https://bin.kv2.dev/~63a825b2e599576ea02b5928

@jing332   闪退

**Comment by jing332** [comment]
替换为 要留空😅

**Comment by Ben1000ten** [comment]
哦

**Comment by XY50** [comment]
好吧

**Comment by MK1909** [comment]
句号和段落能替换不，一句一卡一段一卡顿真头疼

**Comment by jing332** [comment]
@MK1909 句子卡顿emm，是不是把APP内播放打开了。
要替换换行必须在阅读里替换

**Comment by lianbook** [comment]
> 句号和段落能替换不，一句一卡一段一卡顿真头疼

有个办法可以解决你的问题，使用百度朗读接口。或者重新优化段落，阅读是一段一读。把段落重新优化下就行了，

**Comment by jing332** [comment]
> 句号和段落能替换不，一句一卡一段一卡顿真头疼

这是阅读的净化规则，可以把换行替换掉，但也会导致无排版。

> 来自 https://www.coolapk.com/feed/41968748


``` json
{
"group": "常用",
"id": 1671769775394,
"isEnabled": true,
"isRegex": true,
"name": "分行合并",
"order": 50,
"pattern": "(?<=？|”|！|。|……)\\n",
"replacement": "",
"scope": "",
"scopeContent": true,
"scopeTitle": false,
"timeoutMillisecond": 3000
} 
```
