### ISSUE TITLE
希望可以开发成安卓系统的无障碍服务 文字转语音(TTS)输出

### ISSUE THREAD

**Issue by Generalize** [jing332/tts-server-android#3]

**Comment by limne** [comment]
tts服务方式同步的，网络稍微不稳定就会卡，没有这个好用。

**Comment by limne** [comment]
好的，我试试，谢谢

在 2022-10-18 15:45:58，Jing ***@***.***> 写道：


tts服务方式同步的，网络稍微不稳定就会卡，没有这个好用。

我已经加上系统TTS功能了，整理下代码再推送Github。
https://jing332.lanzouw.com/b09hsjrvc
密码:1234
