### ISSUE TITLE
讨论一种对白切换方案的可能性

### ISSUE THREAD

**Issue by Chyiga-n** [jing332/tts-server-android#30]
作者之前做了旁白和对白的分离，不得不说朗读体验真的很好，我很喜欢这个。但是美中不足的是，旁白无法做人物细分，我也知道这个几乎不可能实现，除非写书的人给不同人物的对白用上不同的符号。注意到作者最近加入了随机切换对白的功能，显然还是想在这个方面努力一下的，那么这里我有个建议，不知道技术上有没有可行性：

能不能把一个声音和某个特定文字符号绑定（比如张三），当一段文字中出现这个符号，同时又有双引号（也就是对白）的时候，就使用这个声音来朗读；如果一段文字中含多个这种符号（比如张三对李四说“”），取第一个。

不知道能不能行，希望作者解答

**Comment by GGbond2007** [comment]
这个好像有难度

**Comment by jing332** [comment]
分析器代码写起来过于复杂，而且对白的角色特征并非固定，识别灵动性、准确率低，这将导致听书体验很差。

**Comment by Chyiga-n** [comment]
> 分析器代码写起来过于复杂，而且对白的角色特征并非固定，识别灵动性、准确率低，这将导致听书体验很差。

可能误会了我的意思，我前面也说了细分几乎不可能。我的意思其实就是让用户来自己定义，软件方面要实现的是：给某个声音一个自定义字符的设置，然后用户可以根据自己在看的书输入人物姓名，使得双引号外出现这个名字的对白段落用这个声音进行朗读。

举个例子

  张三说到：“李四，你吃了没”。

TTS配置是 晓晓（张三）

识别到张三两个字，使用晓晓的语音朗读对白“李四，你吃了没”

**Comment by jing332** [comment]
角色特征有时也会出现在对白后面，另外还得考虑到一段文本有多个对话，难处理角色和对白的关联。

**Comment by Chyiga-n** [comment]
> 角色特征有时也会出现在对白后面，另外还得考虑到一段文本有多个对话，难处理角色和对白的关联。

好吧，看起来还是困难重重。。。
