### ISSUE TITLE
希望给无障碍功能再做一个优化，就是所有的下拉列表，希望不是悬浮的，因为这样盲人不是很好操作

### ISSUE THREAD

**Issue by zmyznu** [jing332/tts-server-android#31]
希望把这个功能做好下拉列表，这些都是悬浮的，很不好，尤其是那些使用，盲人智能键盘机的这就有点悲催了，他们得打开触摸屏幕功能摸一下屏幕的角色，才能找到下载列表里的内容，很费劲，还有，触摸屏幕的这些盲人，只喜欢滑动的，那些人找这些角色也不是很好找，所以不希望有悬浮还是改成死定的最好

**Comment by XY50** [comment]
是不是反馈错地方了？这只是听小说用的tts语音引擎，无障碍屏幕阅读器的操作问题，不应该去找谷歌反馈吗？

**Comment by zmyznu** [comment]
我们反馈的是软件问题，OK，谢谢

**Comment by XY50** [comment]
好吧，当我没说

**Comment by jing332** [comment]
主要是因为下拉框用的自定义组件，所以需要手动适配

**Comment by zmyznu** [comment]
那这个好适配吗？主要是

**Comment by jing332** [comment]
有点麻烦，我先看看有没有用于拓展的接口

**Comment by zmyznu** [comment]
好的，谢谢谢谢开发者，辛苦了

**Comment by jing332** [comment]
>盲人智能键盘机的这就有点悲催了，他们得打开触摸屏幕功能摸一下屏幕的角色，才能找到下载列表里的内容

焦点问题已解决

**Comment by jing332** [comment]
我看了下 实现一个对话框不算难，检测如果为无障碍就用对话框，反之使用下拉框。

**Comment by jing332** [comment]
> 我看了下 实现一个对话框不算难，检测如果为无障碍就用对话框，反之使用下拉框。

已更新

**Comment by GGbond2007** [comment]
谢谢大佬，您辛苦了，大佬已经做的够多了就算是下拉框，解说读屏，天坦读屏甚至talk back也很好操作呀，与其单独适配，还不如去让大佬多出一些时间继续优化软件呢，最后还是感谢大佬为这个做了一些适配，现在基本上好操作很多了

**Comment by zmyznu** [comment]
对，的确是谢谢大佬，你说的操作只限于那些能触摸屏幕的那些，只需要滑动的就不是很好操作

**Comment by lianbook** [comment]
盲人怎么用智能手机？没见过

**Comment by GGbond2007** [comment]
在设置的辅助功能无障碍内有专门提供给视障人士的屏幕阅读器，盲人通过语音反馈获取屏幕上的内容，通过特殊手势如左右滑动双击等浏览或激活屏幕上的内容
