### ISSUE TITLE
websocket bad handshake (repeated retries with server connection fail)

### ISSUE THREAD

**Issue by R0ci0-V3rd3al** [jing332/tts-server-android#32]
Hello, good evening, today I tried your application, after trying it for a while in Chinese, I asked why it is not in English? Is there any way that I can contribute in the language, the Microsoft server languages ​​are clear... but there is a problem, a severe bug that I found "websocket bad handshake" restarts retrying to collect endless requests to the server. why is this happening? Does it block the IP or something like that? I am connected by a router that is Chinese in Argentina. greetings from Argentina

**Comment by jing332** [comment]
The `Azure Demo API` has traffic limits, and you can try lowering the audio format.

**Comment by jing332** [comment]
>  I asked why it is not in English? 

Because my English is not good, so APP only have Chinese.

> Is there any way that I can contribute in the language

The APP main string is here:  [strings.xml](https://github.com/jing332/tts-server-android/blob/master/app/src/main/res/values/strings.xml)

**Comment by jing332** [comment]
English is supported: https://github.com/jing332/tts-server-android/actions/runs/3812485613

**Comment by 821938089** [comment]
是不是全局设置里面那个北京微软云节点问题？
我把这个选项打开就好了。

**Comment by jing332** [comment]
不太清楚，我也只在azure接口碰到过bad handshake。

**Comment by jing332** [comment]
我用azure默认格式听几个小时也不会被限制，如果对音质没要求就换成低流量消耗的格式。
