### ISSUE TITLE
请问有没有办法可以减少朗读之间的延迟呢？

### ISSUE THREAD

**Issue by advocatewolf** [jing332/tts-server-android#33]
请问是否有办法可以减少朗读之间的延迟？目前我们发现加载下一组朗读的平均延迟为1秒。

感谢您使用目前版本: https://github.com/jing332/tts-server-android/actions/runs/3812485613

**Comment by jing332** [comment]
没办法，主要来自网络请求耗时，还有如果打开了APP内播放选项，由于无音频缓冲，也会增加间隔时间。

**Comment by advocatewolf** [comment]
是否开启APP内播放选项会减少延迟呢还是会增加呢？

**Comment by jing332** [comment]
增加，具体我写在了APP选项开关的下方。

另外，关于预先缓存的Issue: 
https://github.com/jing332/tts-server-android/issues/19#issuecomment-1343739433

**Comment by jing332** [comment]
```

打开此选项后，将直接使用本APP内置的音频播放器，而非转由系统TTS组件播放。 
由于无需手动解码，且采样率也可在播放中变更，可解决多语音采样率不同时和部分设备的webm格式播放异常问题。 

当然，直接播放也有兼容性问题： 
- 由于并未将原始音频发送到系统TTS组件，所以如果调用TTS者是先缓存后播放机制，即并非由系统播放时，这将会导致缓存时音频为空和意外播放。 
- raw格式依旧不支持，由系统播放。 
- 性能方面相较系统播放略低。 
- 由于内置播放器无音频缓冲，故段落与句子(如已启用分割长句)之间的间隔时间相较系统播放会多出几百毫秒的延迟。

```

**Comment by advocatewolf** [comment]
如果我不使用应用内播放功能怎么办？ 有没有其他方法可以减少延迟？ 也许改变声音的设置？

**Comment by jing332** [comment]
使用默认音频格式，使用Edge接口，挂代理加速

**Comment by advocatewolf** [comment]
谢谢，现在应该够好了。

再次感谢您开发这个应用程序。
