### ISSUE TITLE
可否对系统TTS加入预缓存功能？

### ISSUE THREAD

**Issue by pxladmin** [jing332/tts-server-android#36]
建议可以效仿阅读app请求，不然一延迟高就一段段的，体验很不好。
![Screenshot_2023-01-16-02-32-27-26_c8b102ac7b9ff985df9185de5fad84e4](https://user-images.githubusercontent.com/58046846/212560514-fc7fcccb-626f-4d4b-8b63-ddb55af02ddb.jpg)

**Comment by jing332** [comment]
https://github.com/jing332/tts-server-android/issues/20#issuecomment-1340586095

**Comment by XY50** [comment]
哪怕不能暂停也行，总比每读一句停零点几秒要好

**Comment by XY50** [comment]
长句分割，就是预先缓存，同样是多段音频拼接，朗读却无比流畅

**Comment by jing332** [comment]
看情况，如果段落首句过长也会有明显延迟。

**Comment by jing332** [comment]
不止有不能暂停的问题，安卓开发文档明确写着不让(不能？)这么做，再加上我代码改起来也麻烦，到时有可能碰到各种bug。

**Comment by limne** [comment]
主要是网络延迟，用百度的就不可能有停顿，现在能用就不错了。

**Comment by XY50** [comment]
百度的声音没微软好听,太机械了

**Comment by jing332** [comment]
最新提交我加了系统TTS转发器，可以以HTTP网络请求方式获取安卓系统TTS的音频，配合阅读网络朗读，可解决大部分停顿。

**Comment by XY50** [comment]
阅读中的网络朗读，就和使用内置播放器播放一样每段句子要停顿几百毫秒
![Screenshot_2023-02-02-00-33-42-312_com github jing332 tts_server_android-edit](https://user-images.githubusercontent.com/121076219/216105609-971db337-307e-4684-af89-fb9fa111b52f.jpg)

**Comment by XY50** [comment]
唯一没延迟的方式还是将所有的句子合并，然后开启TTS中的长句分割

**Comment by eromoe** [comment]
@jing332 有教程吗？

**Comment by DaveScream** [comment]
最新提交我加了系统TTS转发器，可以以HTTP网络请求方式获取安卓系统TTS的音频，配合阅读网络朗读，可解决大部分停顿。


How? Example please

**Comment by nhan000** [comment]
Could someone show me how to reduce the pause after each sentence please? I'm using the [T2S](https://play.google.com/store/apps/details?id=hesoft.T2S) app and the pauses make it unusable for me :( Or is it because of the T2S app? What app should I use instead? Thanks a lot!
