### ISSUE TITLE
无障碍的问题请在此反馈

### ISSUE THREAD

**Issue by zmyznu** [jing332/tts-server-android#38]
添加配置里面的。添加本地TTS
有一个警告这个警告没有确定按钮，不知道的还以为关不了，幸亏我知道这个时候该用返回，里面有几个只读默认，当我们点开才知道，标题上写着选择TTS引擎：还有选择语言以及选择语音，这三个下拉列表没有任何提示，当点开才有提示，希望增加提示，谢谢开发，辛苦了

**Comment by jing332** [comment]
唔，这三个忘记初始化无障碍了
