### ISSUE TITLE
Azure接口新增webm-24khz-24kbps只有前几个字的声音

### ISSUE THREAD

**Issue by limne** [jing332/tts-server-android#4]
Azure接口新增webm-24khz-24kbps只有前几个字的声音，然后就下一段了，不知道是哪里的问题？

**Comment by limne** [comment]
应该和这些没关系，测试界面我试了下，所有的webm开头的都是只能前三个字的声音。

**Comment by derQiQ** [comment]
使用web接口试试，可能你手机过系统TTS接口对webm支持不好。另，就人声来说mp3效果并不差。

**Comment by limne** [comment]
嗯，我一直用mp3，看大佬说新增了个最小的就想试试，其实ogg-24khz-16bit-opus最合适，比mp324khz48kbps稍微大一点，但音质更好些，可惜creation不支持，其实只要是24khz的，bps最小，声音也是正常的。

**Comment by limne** [comment]
今天又测试了一下，这个格式使用网页模式是正常的，使用系统tts模式就不行，两种方式有什么区别吗？

**Comment by limne** [comment]
> 

刚才又试了下，这个格式使用系统tts的时候，每段只要前面一个或者两个字发生，然后就跳到下一段了，web接口方式是没问题的，在网页测试这个格式也是没问题的，可以对照下网页测试播放和系统tts播放的区别。

**Comment by limne** [comment]
tts app的声音，只有mp3和ogg正常，ram的断断续续，webm的不能用。

**Comment by limne** [comment]
嗯，如果两个地方没有区别，可能就是你说的，系统tts播放webm音频有问题，而阅读app web接口调用时播放是正常的。

**Comment by limne** [comment]
这就说的通了, 那就用mp3吧，没大多少。
我试了这个https://github.com/benjaminwan/ChineseTtsTflite，感觉不错，如果有好的模型，声音比较自然，如果微软这套最后完全不能用了，可以试试扩展这个。

**Comment by jing332** [comment]
> 嗯，我一直用mp3，看大佬说新增了个最小的就想试试，其实ogg-24khz-16bit-opus最合适，比mp324khz48kbps稍微大一点，但音质更好些，可惜creation不支持，其实只要是24khz的，bps最小，声音也是正常的。

经酷安老哥提醒，以及我的模拟请求测试，发现webm-24kbps并非耗流最小，实际流量是其音频大小的3倍有余。具体看图: 

![R)JZ{FQ()ZWXA0T[VH5Y3WG(1).png](https://user-images.githubusercontent.com/42014615/214547448-566a8a93-e683-4eee-9b55-5ed1f0d19fe5.png)
