### ISSUE TITLE
第三方的语音点击测试，全部都是默认的声音

### ISSUE THREAD

**Issue by XY50** [jing332/tts-server-android#42]
第三方的语音点击测试，全部都是默认的声音
![Screenshot_2023-01-25-00-40-40-798_com github jing332 tts_server_android](https://user-images.githubusercontent.com/121076219/214355183-3cb8f6b3-1e07-44b7-8726-fb28480d6c2a.jpg)

**Comment by jing332** [comment]
说明其tts不支持设置语音，已经测试通过的有: 谷歌语音引擎，ag2s/TTS， 搜狗TTS

**Comment by jing332** [comment]
注意，搜狗TTS语音设置需要手动开启: 设置附加参数 `Boolean forceUse=true` ，或者网络导入现成的配置: https://raw.fastgit.org/jing332/file/main/ttsserver_sougou.json

**Comment by XY50** [comment]
点开的是搜狗，点测试发音全是云希的声音，要么就没声音，这算bug嘛

https://user-images.githubusercontent.com/121076219/214474612-2fd053d3-fd2c-4b57-974d-8b612ac83a1e.mp4

**Comment by jing332** [comment]
TTS引擎倒是选搜狗啊🌚，搜狗那只是显示名称，是不是没装搜狗TTS？

**Comment by XY50** [comment]
> 注意，搜索TTS语语音设置需要手动启动：设置附加参数，或者网络导入现成的配置： [https](https://raw.fastgit.org/jing332/file/main/ttsserver_sougou.json)`Boolean forceUse=true` ://raw.fastgit.org/jing332/file/main/ttsserver_sougou.json[](https://raw.fastgit.org/jing332/file/main/ttsserver_sougou.json)

用的就是这个链接导入的

**Comment by XY50** [comment]
> TTS引倒是选搜狗啊🌚，搜狗那只是显示名称，是不是没装搜狗TTS？

没有安装，搜狗的tts

**Comment by jing332** [comment]
@XY50 这是本地TTS类型的配置，你没装怎么调用🙈

**Comment by XY50** [comment]
好吧，我以为导入这个配置就直接能用了

**Comment by jing332** [comment]
@XY50 搜狗TTS下载地址: https://geminit369.lanzoub.com/iwJAw0l9x8cj

**Comment by jing332** [comment]
装好之后如果还有问题就重新导入配置

**Comment by XY50** [comment]
哦

**Comment by amlyxts** [comment]
搜狗tts可以在发一下吗，什么那个过期了，还有，新发的那个词典有什么用？
