### ISSUE TITLE
可否添加介面語言選項?

### ISSUE THREAD

**Issue by darkj2k** [jing332/tts-server-android#46]
可選擇介面語言，而不是現在的跟隨系統。現在是否僅有簡中跟英文？

**Comment by jing332** [comment]
> 是否僅有簡中跟英文？

是的，僅有簡體中文和英文.

> 可否添加介面語言選項? 

我也正有此意

**Comment by darkj2k** [comment]
速度真快，移到設置會不會更好？另如果要新增繁中我可以怎麼幫忙？

**Comment by jing332** [comment]
也好， 繁中的话我直接简体转换一下就行吧？

**Comment by darkj2k** [comment]
如果需要潤飾或用語不同我再告知。

**Comment by darkj2k** [comment]
請用我校對過的，順便要向你大聲說謝謝。

[strings_zh-TW.zip](https://github.com/jing332/tts-server-android/files/10569825/strings_zh-TW.zip)
