### ISSUE TITLE
獲取失敗與作為備用問題

### ISSUE THREAD

**Issue by darkj2k** [jing332/tts-server-android#48]
更新到0.4_202301301033版本後，僅啟用一個語音選擇朗讀全部，只要沒有勾選 "作為備用" ，就會一直獲取失敗無法使用。

![Screenshot_20230131-090648](https://user-images.githubusercontent.com/3615387/215634728-c68dae81-0cad-4ed9-b66f-470bc0df7d49.jpg)

勾選 "作為備用" 後，雖也會出現斷斷續續的獲取失敗但是可以正常輸出的。我的理解"作為備用"應該是啟用兩個語音以上，當第一個獲取失敗時會自動選擇"作為備用"的語音，我的理解對嗎？

勾選 "作為備用" 後日誌。

![Screenshot_20230131-090037](https://user-images.githubusercontent.com/3615387/215635579-bcac942d-e344-4b7f-9b85-734ab7f2c857.jpg)

另請教啥情況下會產生這個錯誤？
`websocket: closse 1007 (invalid payload data): Unsupported voice.`
因為就算正常播放，日誌裡還是常會看到這行記錄。

**Comment by jing332** [comment]
看日志是因为发音人名称为空，重新编辑保存下你现在的Edge配置就好。

**Comment by darkj2k** [comment]
重編保存依然無效，App整個重置再重新設置後已解決。
