### ISSUE TITLE
[Enhancement]  替換規則ABC音標字體大小

### ISSUE THREAD

**Issue by darkj2k** [jing332/tts-server-android#50]
這字體大小對一般人可能沒問題，但對於像我這種大齡又近視老花的人來說實在是過小了，能否加大字體？

另關於這音標選擇畫面有個想法，因這就固定那幾個字，那麼大一個畫面還要滑動畫面，建議換成橫式排列加大字體方便選擇，如此美觀又方便選擇，像這樣：

A  A1  A2  A3  A4
E  E1  E2  E3  E4
I  I1  I2  I3  I4
O O1 O2 O3 O4
.....
![Screenshot_20230202-121135](https://user-images.githubusercontent.com/3615387/216231002-88e621cf-9241-4e09-af40-999a4d790843.jpg)

**Comment by jing332** [comment]
我会把字体加大并附加如 A1，但由于我开发重点在功能性上，所以UI暂且这样吧😉。

**Comment by darkj2k** [comment]
現階段字型加大即可，感謝您。

**Comment by darkj2k** [comment]
抱歉，我的懶惰讓你誤解了，A1 A2....等我只是舉例，並非要標示上去，那些無意義的可以移除。

![P](https://user-images.githubusercontent.com/3615387/216742176-c00d0c88-5944-493b-861b-aa05a3e20851.jpg)

**Comment by jing332** [comment]
我觉得带上数字也挺好，无障碍屏幕阅读器下也能方便的读出来。不过看着是有些杂乱我会把后面的部分放到无障碍标签里。
