### ISSUE TITLE
系统TTS转发器转发自身bug

### ISSUE THREAD

**Issue by rogueme** [jing332/tts-server-android#51]
转发自身app，多目标语音在线可以缓存，离线tts如谷歌和搜狗则会和已经缓存的所在段落一起播放！
如正在缓存第9段落随机到离线tts，就会和正在播放的第2段一起播放！

**Comment by jing332** [comment]
本地TTS直接播放选项关闭了么？

**Comment by rogueme** [comment]
> 本地TTS直接播放选项关闭了么？

确实,关了就正常了,开始没想到是这个问题
