### ISSUE TITLE
添加配置里面有一个添加插件TTS我想问一下，如果没有插件，能否有一个确定按钮确定按钮的指示是去仓库上选择插件，取消的意思是返回

### ISSUE THREAD

**Issue by zmyznu** [jing332/tts-server-android#52]
如题希望能做到这个样子，谢谢

**Comment by zmyznu** [comment]
另外还有一个问题，在主页的分组里找到自己需要的一个TTS，在后面能显示一个未接标签的一个东西详情还是看录屏吧，描述不清楚，那个点开就报错

**Comment by zmyznu** [comment]
https://user-images.githubusercontent.com/121068584/217173447-bfd2c27a-295d-40e9-8ad1-fcd33737ae49.mp4

**Comment by jing332** [comment]
> SVID_20230207_150848_1.mp4

那个是试听按钮， 我忘记加无障碍标签了， 报错可能是bug

**Comment by jing332** [comment]
试听按钮的文本取自编辑TTS界面的测试文本编辑框， 可能是因为测试文本为空, 所以报空音频异常。
另外这个异常我也会优化下，尽量人性化些。

**Comment by zmyznu** [comment]
好的，谢谢
