### ISSUE TITLE
背景音乐导入不太好用

### ISSUE THREAD

**Issue by XY50** [jing332/tts-server-android#61]
背景音乐导入不太好用，不能自己选，也不能单选，只能顺序播放。
建议改成图中这样，识别目录中音乐后，显示音乐列表然后可单选或多选
![Screenshot_2023-03-31-08-57-59-988_com github jing332 tts_server_android-picsay](https://user-images.githubusercontent.com/121076219/229004947-7b95062d-8bcc-4ffe-9604-203b52cb6711.png)

**Comment by jing332** [comment]
随机播放在右上角更多菜单开启，
我有考虑过这种选择式的，但如果后续更新了文件夹还得勾选，不方便。
