### ISSUE TITLE
微软azure接口报错

### ISSUE THREAD

**Issue by joygu1370** [jing332/tts-server-android#63]
添加TTS时无法选择Azure接口会显示"语音数据加载失败":

![Screenshot_2023-04-07-05-04-58-83_c8b102ac7b9ff985df9185de5fad84e4.jpg](https://user-images.githubusercontent.com/68139176/230579984-8ff302b0-58e3-4f8b-b040-1001f2e4490b.jpg)

**Comment by jing332** [comment]
微软Azure演示接口已失效(原网页已经不存在了), 开发版本已经与Creation接口一起移除掉了
