### ISSUE TITLE
202304072221版本系统TTS转发器bug

### ISSUE THREAD

**Issue by rogueme** [jing332/tts-server-android#64]
阅读App通过系统TTS转发器转发自身系统TTS中内置的微软TTS无音频无声音，小说内容疯狂跳下一段，通过网页端调试也一样是0秒音频

**Comment by rogueme** [comment]
直接用结果也一样，选择本地TTS的话App会崩溃

**Comment by rogueme** [comment]
从异常处理的更新往后都是这个问题

**Comment by jing332** [comment]
关分割长句 或 重新添加内置朗读规则

**Comment by rogueme** [comment]
重新添加朗读规则解决了
