### ISSUE TITLE
请问能加入讯飞开放平台的语音合成 WebAPI 吗？

### ISSUE THREAD

**Issue by grock304** [jing332/tts-server-android#66]
请问能加入讯飞开放平台的语音合成 WebAPI 吗？如果能的话，应该如何操作？谢谢。

**Comment by jing332** [comment]
讯飞支持http GET或POST么？我需要文档

**Comment by jing332** [comment]
看了一下讯飞开放平台是需要用Websocket协议获取音频，我也已对插件TTS做了简单支持

**Comment by jing332** [comment]
我需要一个用于鉴权的auth参数，如果方便的话你可以通过Github主页上的邮箱发给我，我会抽空开发 讯飞WebAPI的插件。

**Comment by grock304** [comment]
文档地址：https://www.xfyun.cn/doc/tts/online_tts/API.html
我看了一下，生成鉴权 authorization 参数，应该主要需要用到 APIKey 和 APISecret，已发你邮箱，先谢过。

**Comment by jing332** [comment]
ok 已收到

**Comment by jing332** [comment]
https://jt12.de/SYV2_1/2023/04/14/15/10/07/16814562076438fc4fc1b21.json

导入插件后点击设置变量按钮，填入id, key和secret即可，特色语音需要自己去讯飞控制台添加。
需配合最新开发版

**Comment by grock304** [comment]
测试成功，感谢。
