### ISSUE TITLE
插件TTS的Azura，风格和角色的选项希望能汉化一下

### ISSUE THREAD

**Issue by bzkmsjy** [jing332/tts-server-android#67]
就之前的Azura演示接口那样的中文选项

**Comment by jing332** [comment]
已更

**Comment by bzkmsjy** [comment]
> 已更

感谢，就是这个翻译文本和之前的插件TTS不太一样，我感觉之前的翻译更好些，风格描述得更形象具体（有很多四字成语），角色里面记得有”年长男性“”年长女性“，要比现在的”老年男“”老年女“看起来舒服些，请问还能不能找到当时插件TTS的翻译呢？如果不行的话至少希望把角色里的翻译优化一下

**Comment by jing332** [comment]
https://github.com/jing332/tts-server-android/blob/master/app/src/main/assets/defaultData/plugin-azure.js#L294-L294

翻译在此，你要有空自己对照Azure帮助文档改下发给我。
https://learn.microsoft.com/zh-cn/azure/cognitive-services/speech-service/speech-synthesis-markup-voice#speaking-styles-and-roles
