### ISSUE TITLE
如何在插件中添加个人azure key ？

### ISSUE THREAD

**Issue by bnlife** [jing332/tts-server-android#68]
没看到在哪里填写![Screenshot_20230418_182046_com.github.jing332.tts_server_android.jpg](https://user-images.githubusercontent.com/38372115/232748410-8673b865-6e63-4846-886d-c488b211d4cb.jpg)

**Comment by jing332** [comment]
确保更新到最新开发版，插件添加保存后，在插件管理界面，点击新添加的Azure条目，然后就可以设置变量了。

**Comment by bnlife** [comment]
非常感谢作者的无私奉献和聪明才智。之前是发布版所以没找到填写key的地方，换了开发版就可以了。但是，还是出现了错误。第81行，音频获取失败。

**Comment by jing332** [comment]
403未授权，检查key和region是否正确

**Comment by bnlife** [comment]
> 403未授权，检查key和region是否正确


感谢作者回复！

Azure 的key是外地的朋友给我的，经朋友核对无误。
我查了一下403错误的可能原因，具体如下https://learn.microsoft.com/zh-cn/azure/digital-twins/troubleshoot-error-403-digital-twins
----------------
由于自己根本不懂代码，只是一个普通的读书爱好者，在看到链接如此复杂的解释便打算放弃了。直接用edge也够用了。

感谢微软，再次感谢作者！

**Comment by jing332** [comment]
检查region是否与key相匹配

**Comment by jing332** [comment]
403这个错误只可能是 region与key不正确

**Comment by jing332** [comment]
呀抱歉是我记错了，401才是代表未授权，
而403代表被服务器禁用，一般是请求太过频繁导致的，看来是你朋友的账号被限制了。

**Comment by bnlife** [comment]
自己注册了azure账号，按照要求填写了key和地区，自然错误。问题在78行，说什么未授权。

**Comment by wyl2000** [comment]
没怎么用过，还真得花点时间折腾下，最后成功了，感谢作者的开发，很好用，免费的与收费的，备用的本地google语音，好用的BGM，这个app太棒了，就等什么时候有本地的TTS达到微软在线的水平了，比自己编译别人的app加入api与地区方便灵活多了。
