### ISSUE TITLE
有些字读的时候有问题

### ISSUE THREAD

**Issue by Maxwell-Wee** [jing332/tts-server-android#69]
例如：树上的果子越大约好 ，虫子越少越好。 这个就读成了  "越越好" 希望修复下

**Comment by jing332** [comment]
本应用仅仅是调用来自本地或网络的TTS，哪来的可修复之说？
如遇到读音问题，可使用替换规则功能，将错字替换为同音字以达到修正目的。

**Comment by Maxwell-Wee** [comment]
这句话放到demo中，就会出现跳读的问题
⾼压危险！应挂在⼯作⼈员上下的铁架、梯⼦上。错误



试试这个，是不是因为编解码的问题出现的这个现象，我把跳读的这个字重新输入就正常了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月20日(周四) 中午12:05
收件人: ***@***.***&gt;;
抄送: "Maxwell ***@***.******@***.***&gt;;
主题: Re: [jing332/tts-server-android] 有些字读的时候有问题 (Issue #69)




 
本应用仅仅是调用来自本地或网络的TTS，哪来的可修复之说？
 如遇到读音问题，可使用替换规则功能，将错字替换为同音字以达到修正目的。

**Comment by Maxwell-Wee** [comment]
今天下午我对比了关于这个跳字的问题，总结出来是字的问题，这个被跳过的字和我们正常输入的字ascall码值有差异，应该识别不出来导致的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月20日(周四) 下午4:55
收件人: ***@***.***&gt;;
抄送: "Maxwell ***@***.******@***.***&gt;;
主题: Re: [jing332/tts-server-android] 有些字读的时候有问题 (Issue #69)




 
你使用的是内置TTS还是插件TTS？ 有尝试过其他TTS吗？ 如本地TTS

**Comment by Maxwell-Wee** [comment]
都无法读出来
