### ISSUE TITLE
Azure API 第85行错误

### ISSUE THREAD

**Issue by lizhulee** [jing332/tts-server-android#70]
evalPluginInfo()..
name: Azure
pluginld: com.microsoft.azure
author:TTS Server
version: 3
isEnabled: true
getSampleRate(..
采样率:24000
onLoad0...
getAudio()... PluginTTS(pluginld=, locale=voice=, data=, pitch=50, volume=50.
rate=50,audioFormat=16000hz|解
码,audioPlayer=PlayerParams(rate=0.0
pitch=0.0.volume=0.0).
audioParams=AudioParams(speed=0.0.
volume=0.0.pitch=0.0).
speechRule=SpeechRulelnfo(target=0,
isStandby=false, tag=, tagRuleld=, tagName=tagData=什, configld=0), plugin=name: Azurepluginld: com.microsoft.azure, author: TTS
Server, version: 3,isEnabled: true)
**第 85 行错误:Unable to resolve host
xn--xhg49sep9azro.tts.speech.microsoft.com"No address associated with hostname**

**Comment by jing332** [comment]
https://learn.microsoft.com/zh-cn/azure/cognitive-services/speech-service/rest-text-to-speech?source=recommendations&tabs=streaming#prebuilt-neural-voices

找不到域名，可能是网络/DNS问题，也有可能是region不对

**Comment by lizhulee** [comment]
region 没设置对。 现在报403 错误。 刚买的api

**Comment by jing332** [comment]
403啊，那可能是账号被微软限制了
