### ISSUE TITLE
如何在自己的 Android TTS APP中获取当前选择的说话人？

### ISSUE THREAD

**Issue by haveyouwantto** [jing332/tts-server-android#74]
我正在使用您的 TTS APP，并想在我的APP中获取当前选中的语音。我尝试过在 `onLoadVoice` 方法中获取语音名称，但是该方法似乎不会被调用，而且 `request.getVoiceName()` 返回的也是 null。

您是否可以提供一些指导，以便我可以在我的APP中获取当前选择的说话人？

谢谢！
![1682174047729](https://user-images.githubusercontent.com/20786993/233790904-9753db39-0664-4bb1-8e73-381e5c46270a.jpg)

**Comment by jing332** [comment]
https://github.com/ag2s20150909/TTS/blob/e55e3ed93fbd46084a7ac4dc5d62fc6cf592da5f/app/src/main/java/me/ag2s/tts/services/TTSService.java#L646

此APP的代码应该对你有帮助🙂

**Comment by haveyouwantto** [comment]
解决了，问题出在没有实现`onGetDefaultVoiceNameFor`方法
