### ISSUE TITLE
优化TTS引擎在大量说话人情况下的性能

### ISSUE THREAD

**Issue by haveyouwantto** [jing332/tts-server-android#76]
我在使用TTS引擎的过程中遇到了一个问题：当有大量说话人时，比如500个，程序响应非常慢。为了提高性能，我建议对TTS引擎进行优化。

建议实现以下两个功能：

缓存说话人列表：在启动TTS时，将所有说话人的列表缓存到内存中。这样，当用户打开TTS引擎时，程序可以直接从内存中读取列表，而不需要每次从上游TTS引擎获取。这样可以减少性能开销和提高响应速度。

添加搜索说话人的功能：在列表中添加一个搜索框，用户可以根据关键字搜索所需的说话人。这样可以减少用户的操作时间，提高使用体验。

**Comment by jing332** [comment]
缓存应该是目标TTS App做的事情，TTS Server作为客户端只能做到调用目标TTS，而无法干预其内部缓存实现。
所以，你应在TextToSpeechService中根据voiceName维护一个缓存集合，然后定时清理长时间未使用的模型。

**Comment by haveyouwantto** [comment]
根据我的观察来看，TTS Server似乎每切换一次角色就会读取一次角色列表。我已经对获取这个角色列表的方法进行了缓存。
![image](https://user-images.githubusercontent.com/20786993/233874218-e91e5125-ccde-421d-aca1-5e6c21421a9c.png)

**Comment by jing332** [comment]
是的，因为需要通过voiceName找到对应Voice对象

**Comment by haveyouwantto** [comment]
tts server能不能缓存这个voice对象的列表呢

**Comment by jing332** [comment]
你方便把demo apk发给我测试么？我这边好针对性优化下

**Comment by haveyouwantto** [comment]
[这个](https://github.com/haveyouwantto/VITSClient)

**Comment by jing332** [comment]
既然是Http API，为什么不直接开发TTS Server的插件TTS呢？

这样能把性能损耗降到最低，还能使用到流播放, 自动重试功能。

**Comment by jing332** [comment]
https://sy.mgz6.cc/shuyuan/01db7969528b7e57e03e0ddeb07ca1f7.json

插件列表，从网络链接导入

**Comment by haveyouwantto** [comment]
我刚刚查看了一下，应该已经解决了性能问题。现在我们可以考虑添加一个角色搜索的功能。

**Comment by jing332** [comment]
今晚我看看能否成功搭建服务，如果成功，我会把插件成品发给你。
当然你也可以参考插件列表自行开发。

**Comment by jing332** [comment]
> 我刚刚测试了一下我的app，应该已经解决了性能问题。现在我们可以考虑添加一个角色搜索的功能。

我会尝试给下拉框加个搜索过滤功能

**Comment by jing332** [comment]
@haveyouwantto  已更新~

**Comment by haveyouwantto** [comment]
非常感谢！我需要一些时间来进行测试，看看是否还有其他问题。

**Comment by haveyouwantto** [comment]
OK,目前没发现问题。

**Comment by jing332** [comment]
@haveyouwantto   `FileNotFoundError: [Errno 2] No such file or directory: '../models/SayaSS-zh-ja/config.json'
`
MoeGoe 有没有整理好的models包

**Comment by haveyouwantto** [comment]
目前我用的是[这个模型](https://huggingface.co/spaces/zomehwh/vits-uma-genshin-honkai/tree/main/model)，中文能力比较好
