### ISSUE TITLE
界面按钮翻倍问题

### ISSUE THREAD

**Issue by XY50** [jing332/tts-server-android#79]
经常出现双份按钮，每次莫名其妙选项就翻倍了
另外在状态栏上就是切换深色或浅色模式，选项就会百分百翻倍
![Screenshot_2023-05-02-12-34-58-056_com github jing332 tts_server_android-edit](https://user-images.githubusercontent.com/121076219/235580066-7630089a-8aa8-4ee2-931e-37280d5bf698.jpg)
![Screenshot_2023-05-02-12-34-06-837_com github jing332 tts_server_android-edit](https://user-images.githubusercontent.com/121076219/235580093-bb934e01-7ad4-4e5d-8b20-7f9791d58e39.jpg)

**Comment by XY50** [comment]
还有应用后台后再重新点开，分组和全部按钮有50%的几率消失
![Screenshot_2023-05-02-12-49-05-635_com github jing332 tts_server_android-edit](https://user-images.githubusercontent.com/121076219/235581707-b3838c95-9503-4abf-b05b-09328d64afca.jpg)

**Comment by XY50** [comment]
https://user-images.githubusercontent.com/121076219/235583302-407dc5e0-4e06-4860-833d-9f9d2164ebb1.mp4

**Comment by jing332** [comment]
🙄bug之前也有不过几率低，这次加了动画就导致ui生命周期易错乱。
