### ISSUE TITLE
说一下最近发现的bug。

### ISSUE THREAD

**Issue by finalsec** [jing332/tts-server-android#80]
首先非常感谢大佬做的APP，各种体验真的吊打其他Android tts。其次想说一下最近发现的bug，如果发的地方不对还请原谅。
1.背景音乐选择，使用APP内置的文件选择器看不到MP3文件，不选择文件直接返回APP会直接卡死。
2.导入api，鼓捣了一下午发现安装新版本的时候要把旧版本卸载才可以，直接安装新版本默认导入默认配置文件不会更新。

**Comment by XY50** [comment]
我补充一下
使用APP内置文件选择器取消返回的时候，返回键就会失效，并不是app卡死
使用顶部的返回按钮返回后，菜单上的所有按钮会丢失
![Screenshot_2023-05-07-01-50-02-397_com github jing332 tts_server_android-edit](https://user-images.githubusercontent.com/121076219/236639366-ff2280ed-d46a-4690-aa12-d89010c0d0aa.jpg)

点击编辑按钮的时候，界面会重合0.5秒，以前的版本没这个问题
![Screenshot_2023-05-03-10-47-22-934_com github jing332 tts_server_android](https://user-images.githubusercontent.com/121076219/236639389-b5fe88da-9389-4d05-b33d-91b55af3e589.jpg)

希望大佬早点修复

**Comment by jing332** [comment]
新旧版本差异不大，退回旧版本吧

**Comment by zycboss** [comment]
Dev版本直接覆盖安装打开会白屏卡死，必须整个卸载重装才行，应该是老版本配置文件不兼容新Dev版
