### ISSUE TITLE
想咨询一下有关于流式播放音频的问题

### ISSUE THREAD

**Issue by laulguo** [jing332/tts-server-android#82]
目前是发现需要打开流式播放音频+ExoPlayer播放，然后好像EDGE接口Go-Native和Java-OkHTTP都可以做到流式播放？但似乎GO-Native有时候会失效，需要切一下接口才能够做到流式播放，而Java-OkHTTP会莫名的卡住和跳句子

**Comment by jing332** [comment]
go版本是完整下载后播放，流播是兼容的
