### ISSUE TITLE
为对话识别添加方引号的支持

### ISSUE THREAD

**Issue by haveyouwantto** [jing332/tts-server-android#83]
为了更好地识别对话并方便设置朗读角色，可以添加对方引号`「」`的支持，因为在许多轻小说中都会使用这种引号。

**Comment by jing332** [comment]
改下朗读脚本或者用替换规则

**Comment by haveyouwantto** [comment]
我已经通过改规则的方式添加了，不过我希望能够成为默认的行为

**Comment by jing332** [comment]
受众面不一，改动可能会影响到部分用户。
