### ISSUE TITLE
TTS server no longer work with android background speech synthesis settings

### ISSUE THREAD

**Issue by R0ci0-V3rd3al** [jing332/tts-server-android#84]
Hello. how are you? Sorry for writing here, now that I've tried the latest version of your app I'm seeing good translation but there was a problem. TTS server no longer work with android background speech synthesis settings, even if I put Chinese or another language from Microsoft the application stops. I tried with other tts to rule out that it was not my android and it turns out that with other tts they work

**Comment by jing332** [comment]
Can you provide more information?

**Comment by R0ci0-V3rd3al** [comment]
Hello :D , no problem now works fine now , It was already fixed when you updated it in the latest versions. now if it connects I thought at first that it was the fault of the pattern lock on android that was preventing the proper functioning of the tts integration. ^_^ Thank you very much for answering you can close this thread if you wish
