### ISSUE TITLE
段落停顿时间，该怎么设置呢？

### ISSUE THREAD

**Issue by ffgg536956** [jing332/tts-server-android#89]
我知道tts-server可以设置 朗读语速，但是我在tts-server以及阅读APP里面找不到设置 段落停顿。请问段落停顿时间，该怎么设置呢？

**Comment by eromoe** [comment]
我也想知道，读小说的时候每句话之间的停顿感太强了

**Comment by zycboss** [comment]
用 [静读天下](https://www.yxssp.com/25555.html)
可以设置语音朗读内容划分方式，选 整段 就会每段文字发送请求，段落间就会停顿，停顿时间可以调整，整页朗读就是每一页停顿一次

**Comment by eromoe** [comment]
在用legado 没选项就比较尴尬

**Comment by limne** [comment]
貌似没有选项可设置，只和网络状况有关，目前只能用edge，选24k48kbps就可以了

**Comment by moodHappy** [comment]
我结合浏览器听新闻也是一个逗号发送一次请求，停顿太明显。但是用阅读app听书就是一大段发送请求，停顿，不知道怎么回事。

**Comment by eromoe** [comment]
@moodHappy 用什么插件结合的？

**Comment by moodHappy** [comment]
> Reference

雨见浏览器，就是一句话一停顿，不能像在阅读里那样连贯

**Comment by moodHappy** [comment]
@eromoe 雨见浏览器，就是一句话一停顿，不能像在阅读里那样连贯
