### ISSUE TITLE
关于多音字，大佬是否考虑构建？

### ISSUE THREAD

**Issue by LeanFly** [jing332/tts-server-android#9]
最近使用了这个tts安卓应用，效果比miui自己的tts要好很多，不过目前发现对多音字不支持，是否考虑增加一个支持多音字的版本呢？如果需要相应的注音的话，可以提供支持。

**Comment by jing332** [comment]
APP本身并不会合成音频，而是通过调用Edge浏览器的大声朗读、Azure或Speech Studio这些逆向抓包出来的接口。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月17日(周四) 中午11:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jing332/tts-server-android] 关于多音字，大佬是否考虑构建？ (Issue #9)




 
最近使用了这个tts安卓应用，效果比miui自己的tts要好很多，不过目前发现对多音字不支持，是否考虑增加一个支持多音字的版本呢？如果需要相应的注音的话，可以提供支持。

**Comment by jing332** [comment]
除edge接口外，另两个微软都支持发音纠正，但略微麻烦，等哪天一时兴起或许会支持吧。🙄



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月17日(周四) 中午11:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jing332/tts-server-android] 关于多音字，大佬是否考虑构建？ (Issue #9)




 
最近使用了这个tts安卓应用，效果比miui自己的tts要好很多，不过目前发现对多音字不支持，是否考虑增加一个支持多音字的版本呢？如果需要相应的注音的话，可以提供支持。

**Comment by limne** [comment]
tts app那边有，但貌似需要自己配置。。。

**Comment by jing332** [comment]
或许不一定非要用ssml标签替换，我直接做个和阅读APP一样的净化替换功能，将多音字替换成同音字或注音就好。

**Comment by limne** [comment]
可以，其实不多，就是，多重，一重二重，重量，同行（xing）同行（hang）一行，这些。。

**Comment by lianbook** [comment]
另外两个免费试用的接口好像失效了。不过可以改成收费接口

**Comment by jing332** [comment]
emmm我没有key，所以没法调试。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月19日(周六) 下午3:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jing332/tts-server-android] 关于多音字，大佬是否考虑构建？ (Issue #9)




 
另外两个免费试用的接口好像失效了。不过可以改成收费接口

**Comment by lianbook** [comment]
注册个账号，有免费试用额度

**Comment by jing332** [comment]
没有visa卡，github教育版我也没有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月19日(周六) 晚上10:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jing332/tts-server-android] 关于多音字，大佬是否考虑构建？ (Issue #9)




 
注册个账号，有免费试用额度

**Comment by jing332** [comment]
开发版加了替换功能，你从Actions下载试试看。

**Comment by jing332** [comment]
那是ssml标签的格式，我为了适配edge，所以用更简单的直接替换实现
