### ISSUE TITLE
如何在朗读不同语言在时切换自如 how to switch between mutiple languages automatically during reading

### ISSUE THREAD

**Issue by delicacyyy** [jing332/tts-server-android#90]
使用openai翻译出双语书籍后 目前普通话可以朗读英文 但反过来就不行 而且用普通话朗读英文非常不自然 所以请教一下如何通过一些设置手法实现根据不同语言来回自由切换目标tts 英文的就英语 简体字就普通话 繁体就粤语

**Comment by eromoe** [comment]
这个得用一个语言模型预先检测下面一句话里那些话是什么语言，然后调用对应的TTS，目前的阅读软件都不会这么折腾的。
