### ISSUE TITLE
最新正式版小小bug

### ISSUE THREAD

**Issue by XY50** [jing332/tts-server-android#92]
1.使用内置文件选择器添加音乐时直接返回，返回键会失效，使用顶部按钮返回后，首页顶部按钮会彻底消失
https://github.com/jing332/tts-server-android/assets/121076219/6c7e164e-938c-4f6b-8232-4c27402ed369

2.单独授权所有文件访问权，可以通过系统选择器添加音乐，两个储存权限都授权后就无法添加音乐了，内置选择器也无法显示音乐
https://github.com/jing332/tts-server-android/assets/121076219/3a9c3ab3-8728-4b3c-bbdf-e52f975b8ee3

**Comment by jing332** [comment]
系统存储权限问题, APP无权干预也无法解决
