### ISSUE TITLE
所有的英文发音引擎全都不能用了 昨天还可以的 请查实

### ISSUE THREAD

**Issue by rick999999** [jing332/tts-server-android#93]
所有的英文发音引擎全都不能用了 昨天还可以的 请查实

**Comment by rick999999** [comment]
收到closed 信息 去看了下 还是Null array 报错呀，问题任何存在呀 请查实？是在下一个版本中修复吗？谢谢

**Comment by jing332** [comment]
测试文本不要用中文，英语发音人他咋给你朗读中文😂？

**Comment by rick999999** [comment]
> 测试文本不要用中文，英语发音人他咋给你朗读中文？

我点的是你右边三个点下面的试听 按钮 之前是可以的，你说的对 看来问题出在试听按钮上 ，让它读英文文章是可以读的 ，我之前忽略了这个问题 ，我还纳闷了 怎么中文可以读其它语言都不可以读了，

但是还是试听按钮还是有用的 因为有的时候需要选择音色，当然非常感谢 指出 ，感谢
