### ISSUE TITLE
“設置對話最小匹配漢字數”功能不見了

### ISSUE THREAD

**Issue by miaomiaorun** [jing332/tts-server-android#94]
如題，更新之後，原本的“設置對話最小匹配漢字數”功能不見了，希望這個功能可以加回來，感謝大神的付出！

**Comment by jing332** [comment]
使用替换规则代替
https://github.com/jing332/tts-server-android/issues/41#issuecomment-1401652618

**Comment by derQiQ** [comment]
正则查找：(“)(.{1,5})(”)
正则替换：$2

新版纯手工难倒97%的人，旧版只要填【5】数字就能实现[哭笑]。
