### ISSUE TITLE
语音自动改变

### ISSUE THREAD

**Issue by linmister** [jing332/tts-server-android#98]
最新的0.8版本微软azure使用一段时间后，角色的语音会发生改变，重新点击一次试听可以恢复，但过一段时间又会自动改变

**Comment by jing332** [comment]
请您详细描述下当前的TTS配置，也可以把截图发过来。

**Comment by jing332** [comment]
角色转变指的是 微软角色扮演(如：中年男，小男孩)，
还是发音人的转变 （如：晓晓，云希） ?

**Comment by linmister** [comment]
![微信图片_20230715192655](https://github.com/jing332/tts-server-android/assets/51257978/0292052e-a3ca-4234-ab3e-90a2aa84c0de)
这是我的配置，不是角色转变，因为晓晓没有角色选择，我晓晓配的抒情比较温柔的，播放一段时间就变成那种不温柔的，有点像音高变了。

**Comment by jing332** [comment]
[fix: 插件TTS的附加数据混乱问题](https://github.com/jing332/tts-server-android/actions/runs/5635518708) 
已修复

**Comment by jing332** [comment]
[fix: 插件TTS 对象数据不更新](https://github.com/jing332/tts-server-android/actions/runs/5636675765)
再次修复😂

**Comment by jing332** [comment]
[fix: 插件TTS 对象数据不更新](https://github.com/jing332/tts-server-android/actions/runs/5637083960)
这次经过我缜密的测试，可以了 hhh
