### ISSUE TITLE
添加阿里云语音合成

### ISSUE THREAD

**Issue by Benjamin-Watson0** [jing332/tts-server-android#99]
相比微软云,合成效果已经差不多了。比如多情感系列和文学系列。

申请起来也更容易，更便宜，微软云用起来门槛很高。

您可以加进来，可以试试嘛🥳

桌面端访问网站即可体验
https://ai.aliyun.com/nls/

**Comment by jing332** [comment]
> 

朋友呀，恕我直言。 你是不看项目的README么：
> TTS插件
程序已内置Azure官方接口的TTS插件: 插件管理 -> 右上角添加 -> 保存 -> 设置变量 -> 填入Key与Region即可
